# Generated by Django 3.1.3 on 2023-04-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210426_0742'),
        ('tweets', '0002_auto_20230425_1222'),
    ]

    operations = [
    ]
